"""Initial schema

Revision ID: bffa49d195ad
Revises: 
Create Date: 2026-10-03 12:30:28.364364

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bffa49d195ad'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('organizations',
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('organization_code', sa.String(length=50), nullable=False),
    sa.Column('status', sa.Enum('ACTIVE', 'INACTIVE', 'SUSPENDED', name='organizationstatus', native_enum=False, length=50), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('organizations', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_organizations_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_organizations_organization_code'), ['organization_code'], unique=True)
        batch_op.create_index(batch_op.f('ix_organizations_status'), ['status'], unique=False)

    op.create_table('sites',
    sa.Column('organization_id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('site_code', sa.String(length=50), nullable=False),
    sa.Column('site_type', sa.Enum('HOME', 'BUILDING', 'FACTORY', 'OFFICE', 'AGRICULTURE', 'PUMP_STATION', 'WATER_PLANT', 'WAREHOUSE', 'OTHER', name='sitetype', native_enum=False, length=50), nullable=False),
    sa.Column('location', sa.String(length=255), nullable=True),
    sa.Column('timezone', sa.String(length=64), nullable=False),
    sa.Column('status', sa.Enum('ACTIVE', 'INACTIVE', 'SUSPENDED', 'MAINTENANCE', name='sitestatus', native_enum=False, length=50), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('organization_id', 'site_code', name='uq_sites_org_code')
    )
    with op.batch_alter_table('sites', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_sites_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_sites_organization_id'), ['organization_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_sites_site_code'), ['site_code'], unique=False)
        batch_op.create_index(batch_op.f('ix_sites_status'), ['status'], unique=False)

    op.create_table('users',
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('role', sa.Enum('SUPER_ADMIN', 'ORGANIZATION_ADMIN', 'SITE_MANAGER', 'STATION_OPERATOR', 'TECHNICIAN', 'VIEWER', 'OWNER', 'FAMILY_MEMBER', name='userrole', native_enum=False, length=50), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('organization_id', sa.Uuid(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_users_email'), ['email'], unique=True)
        batch_op.create_index(batch_op.f('ix_users_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_users_organization_id'), ['organization_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_users_role'), ['role'], unique=False)

    op.create_table('stations',
    sa.Column('site_id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('station_code', sa.String(length=50), nullable=False),
    sa.Column('station_type', sa.Enum('HOME_PUMP', 'WATER_SUPPLY', 'BOREWELL', 'IRRIGATION', 'INDUSTRIAL', 'RO_PLANT', 'TREATMENT', 'DISTRIBUTION', 'OTHER', name='stationtype', native_enum=False, length=50), nullable=False),
    sa.Column('location', sa.String(length=255), nullable=True),
    sa.Column('timezone', sa.String(length=64), nullable=False),
    sa.Column('description', sa.String(length=500), nullable=True),
    sa.Column('status', sa.Enum('ACTIVE', 'INACTIVE', 'SUSPENDED', 'MAINTENANCE', name='stationstatus', native_enum=False, length=50), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['site_id'], ['sites.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('site_id', 'station_code', name='uq_stations_site_code')
    )
    with op.batch_alter_table('stations', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_stations_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_stations_site_id'), ['site_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_stations_station_code'), ['station_code'], unique=False)
        batch_op.create_index(batch_op.f('ix_stations_status'), ['status'], unique=False)

    op.create_table('audit_logs',
    sa.Column('organization_id', sa.Uuid(), nullable=True),
    sa.Column('site_id', sa.Uuid(), nullable=True),
    sa.Column('station_id', sa.Uuid(), nullable=True),
    sa.Column('actor_user_id', sa.Uuid(), nullable=True),
    sa.Column('actor_type', sa.Enum('USER', 'SYSTEM', 'CONTROLLER', 'AUTOMATION', name='auditactortype', native_enum=False), nullable=False),
    sa.Column('action', sa.Enum('CREATE', 'UPDATE', 'DELETE', 'LOGIN', 'LOGOUT', 'START', 'STOP', 'RESET', 'EMERGENCY_STOP', 'CONFIGURE', 'ENABLE', 'DISABLE', 'ACKNOWLEDGE', 'EXPORT', 'IMPORT', 'OTHER', name='auditaction', native_enum=False), nullable=False),
    sa.Column('resource_type', sa.String(length=100), nullable=False),
    sa.Column('resource_id', sa.Uuid(), nullable=True),
    sa.Column('action_description', sa.String(length=500), nullable=False),
    sa.Column('audit_metadata', sa.JSON(), nullable=True),
    sa.Column('ip_address', sa.String(length=45), nullable=True),
    sa.Column('user_agent', sa.String(length=500), nullable=True),
    sa.Column('occurred_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['actor_user_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['site_id'], ['sites.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['station_id'], ['stations.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('audit_logs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_audit_logs_actor_user_id'), ['actor_user_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_audit_logs_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_audit_logs_organization_id'), ['organization_id'], unique=False)
        batch_op.create_index('ix_audit_logs_organization_id_occurred_at', ['organization_id', 'occurred_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_audit_logs_resource_id'), ['resource_id'], unique=False)
        batch_op.create_index('ix_audit_logs_resource_type_resource_id', ['resource_type', 'resource_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_audit_logs_site_id'), ['site_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_audit_logs_station_id'), ['station_id'], unique=False)

    op.create_table('controllers',
    sa.Column('station_id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('controller_code', sa.String(length=50), nullable=False),
    sa.Column('device_uid', sa.String(length=100), nullable=False),
    sa.Column('controller_type', sa.Enum('ESP32', 'ESP32_ETHERNET', 'ESP32_4G', 'PLC', 'INDUSTRIAL_GATEWAY', 'OTHER', name='controllertype', native_enum=False, length=50), nullable=False),
    sa.Column('status', sa.Enum('ACTIVE', 'INACTIVE', 'MAINTENANCE', 'OFFLINE', 'DECOMMISSIONED', name='controllerstatus', native_enum=False, length=50), nullable=False),
    sa.Column('firmware_version', sa.String(length=50), nullable=True),
    sa.Column('ip_address', sa.String(length=45), nullable=True),
    sa.Column('mac_address', sa.String(length=17), nullable=True),
    sa.Column('last_seen_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('description', sa.String(length=500), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['station_id'], ['stations.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('station_id', 'controller_code', name='uq_controllers_station_code')
    )
    with op.batch_alter_table('controllers', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_controllers_controller_code'), ['controller_code'], unique=False)
        batch_op.create_index(batch_op.f('ix_controllers_device_uid'), ['device_uid'], unique=True)
        batch_op.create_index(batch_op.f('ix_controllers_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_controllers_station_id'), ['station_id'], unique=False)

    op.create_table('station_settings',
    sa.Column('station_id', sa.Uuid(), nullable=False),
    sa.Column('timezone', sa.String(length=64), nullable=False),
    sa.Column('auto_stop_on_tank_full', sa.Boolean(), nullable=False),
    sa.Column('water_level_threshold', sa.Numeric(precision=20, scale=6), nullable=True),
    sa.Column('turbidity_threshold', sa.Numeric(precision=20, scale=6), nullable=True),
    sa.Column('default_timer_seconds', sa.Integer(), nullable=True),
    sa.Column('offline_alert_enabled', sa.Boolean(), nullable=False),
    sa.Column('offline_timeout_seconds', sa.Integer(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['station_id'], ['stations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('station_settings', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_station_settings_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_station_settings_station_id'), ['station_id'], unique=True)

    op.create_table('motors',
    sa.Column('controller_id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('motor_code', sa.String(length=50), nullable=False),
    sa.Column('motor_type', sa.Enum('WATER_PUMP', 'SUBMERSIBLE_PUMP', 'BOREWELL_PUMP', 'BOOSTER_PUMP', 'IRRIGATION_PUMP', 'CENTRIFUGAL_PUMP', 'INDUSTRIAL_PUMP', 'OTHER', name='motortype', native_enum=False, length=50), nullable=False),
    sa.Column('status', sa.Enum('OFFLINE', 'OFF', 'ON', 'STARTING', 'STOPPING', 'FAULT', 'MAINTENANCE', 'DISABLED', name='motorstatus', native_enum=False, length=50), nullable=False),
    sa.Column('rated_power', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('description', sa.String(length=500), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['controller_id'], ['controllers.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('controller_id', 'motor_code', name='uq_motors_controller_code')
    )
    with op.batch_alter_table('motors', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_motors_controller_id'), ['controller_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_motors_id'), ['id'], unique=False)

    op.create_table('sensors',
    sa.Column('controller_id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('sensor_code', sa.String(length=50), nullable=False),
    sa.Column('sensor_type', sa.Enum('WATER_LEVEL', 'TURBIDITY', 'FLOW', 'PRESSURE', 'TEMPERATURE', 'HUMIDITY', 'CURRENT', 'VOLTAGE', 'PH', 'OTHER', name='sensortype', native_enum=False, length=50), nullable=False),
    sa.Column('status', sa.Enum('ACTIVE', 'INACTIVE', 'FAULT', 'MAINTENANCE', 'DISABLED', name='sensorstatus', native_enum=False, length=50), nullable=False),
    sa.Column('description', sa.String(length=500), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['controller_id'], ['controllers.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('controller_id', 'sensor_code', name='uq_sensors_controller_code')
    )
    with op.batch_alter_table('sensors', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_sensors_controller_id'), ['controller_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_sensors_id'), ['id'], unique=False)

    op.create_table('automation_rules',
    sa.Column('station_id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('description', sa.String(length=500), nullable=True),
    sa.Column('rule_type', sa.Enum('WATER_LEVEL', 'TURBIDITY', 'TIMER', name='automationruletype', native_enum=False, length=50), nullable=False),
    sa.Column('status', sa.Enum('ACTIVE', 'INACTIVE', name='automationrulestatus', native_enum=False, length=50), nullable=False),
    sa.Column('sensor_id', sa.Uuid(), nullable=True),
    sa.Column('operator', sa.Enum('GREATER_THAN', 'GREATER_THAN_OR_EQUAL', 'LESS_THAN', 'LESS_THAN_OR_EQUAL', 'EQUAL', name='automationoperator', native_enum=False, length=50), nullable=True),
    sa.Column('threshold_value', sa.Numeric(precision=20, scale=6), nullable=True),
    sa.Column('threshold_unit', sa.String(length=32), nullable=True),
    sa.Column('duration_seconds', sa.Integer(), nullable=True),
    sa.Column('motor_id', sa.Uuid(), nullable=False),
    sa.Column('action', sa.Enum('START_MOTOR', 'STOP_MOTOR', 'RESET_MOTOR', 'EMERGENCY_STOP_MOTOR', name='automationaction', native_enum=False, length=50), nullable=False),
    sa.Column('cooldown_seconds', sa.Integer(), nullable=True),
    sa.Column('created_by', sa.Uuid(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['motor_id'], ['motors.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['sensor_id'], ['sensors.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['station_id'], ['stations.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('automation_rules', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_automation_rules_created_by'), ['created_by'], unique=False)
        batch_op.create_index(batch_op.f('ix_automation_rules_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_automation_rules_motor_id'), ['motor_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_automation_rules_sensor_id'), ['sensor_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_automation_rules_station_id'), ['station_id'], unique=False)
        batch_op.create_index('ix_automation_rules_station_status', ['station_id', 'status'], unique=False)

    op.create_table('motor_commands',
    sa.Column('motor_id', sa.Uuid(), nullable=False),
    sa.Column('command_type', sa.Enum('START', 'STOP', 'RESET', 'EMERGENCY_STOP', name='commandtype', native_enum=False, length=50), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'SENT', 'ACKNOWLEDGED', 'EXECUTED', 'FAILED', 'TIMEOUT', name='commandstatus', native_enum=False, length=50), nullable=False),
    sa.Column('requested_by', sa.Uuid(), nullable=True),
    sa.Column('command_payload', sa.JSON(), nullable=True),
    sa.Column('requested_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('sent_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('acknowledged_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('executed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('failed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('error_message', sa.String(length=1000), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['motor_id'], ['motors.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['requested_by'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('motor_commands', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_motor_commands_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_motor_commands_motor_id'), ['motor_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_motor_commands_requested_by'), ['requested_by'], unique=False)

    op.create_table('motor_events',
    sa.Column('motor_id', sa.Uuid(), nullable=False),
    sa.Column('event_type', sa.Enum('STARTED', 'STOPPED', 'FAULT', 'RESET', 'EMERGENCY_STOP', 'OFFLINE', 'ONLINE', name='motoreventtype', native_enum=False, length=50), nullable=False),
    sa.Column('source', sa.Enum('USER', 'CONTROLLER', 'SYSTEM', 'SENSOR', 'AUTOMATION', name='motoreventsource', native_enum=False, length=50), nullable=False),
    sa.Column('occurred_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('event_payload', sa.JSON(), nullable=True),
    sa.Column('description', sa.String(length=500), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['motor_id'], ['motors.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('motor_events', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_motor_events_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_motor_events_motor_id'), ['motor_id'], unique=False)

    op.create_table('telemetry_readings',
    sa.Column('sensor_id', sa.Uuid(), nullable=False),
    sa.Column('value', sa.Numeric(precision=20, scale=6), nullable=False),
    sa.Column('unit', sa.String(length=32), nullable=False),
    sa.Column('occurred_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('metadata', sa.JSON(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['sensor_id'], ['sensors.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('telemetry_readings', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_telemetry_readings_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_telemetry_readings_sensor_id'), ['sensor_id'], unique=False)
        batch_op.create_index('ix_telemetry_readings_sensor_id_occurred_at', ['sensor_id', 'occurred_at'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('telemetry_readings', schema=None) as batch_op:
        batch_op.drop_index('ix_telemetry_readings_sensor_id_occurred_at')
        batch_op.drop_index(batch_op.f('ix_telemetry_readings_sensor_id'))
        batch_op.drop_index(batch_op.f('ix_telemetry_readings_id'))

    op.drop_table('telemetry_readings')
    with op.batch_alter_table('motor_events', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_motor_events_motor_id'))
        batch_op.drop_index(batch_op.f('ix_motor_events_id'))

    op.drop_table('motor_events')
    with op.batch_alter_table('motor_commands', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_motor_commands_requested_by'))
        batch_op.drop_index(batch_op.f('ix_motor_commands_motor_id'))
        batch_op.drop_index(batch_op.f('ix_motor_commands_id'))

    op.drop_table('motor_commands')
    with op.batch_alter_table('automation_rules', schema=None) as batch_op:
        batch_op.drop_index('ix_automation_rules_station_status')
        batch_op.drop_index(batch_op.f('ix_automation_rules_station_id'))
        batch_op.drop_index(batch_op.f('ix_automation_rules_sensor_id'))
        batch_op.drop_index(batch_op.f('ix_automation_rules_motor_id'))
        batch_op.drop_index(batch_op.f('ix_automation_rules_id'))
        batch_op.drop_index(batch_op.f('ix_automation_rules_created_by'))

    op.drop_table('automation_rules')
    with op.batch_alter_table('sensors', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_sensors_id'))
        batch_op.drop_index(batch_op.f('ix_sensors_controller_id'))

    op.drop_table('sensors')
    with op.batch_alter_table('motors', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_motors_id'))
        batch_op.drop_index(batch_op.f('ix_motors_controller_id'))

    op.drop_table('motors')
    with op.batch_alter_table('station_settings', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_station_settings_station_id'))
        batch_op.drop_index(batch_op.f('ix_station_settings_id'))

    op.drop_table('station_settings')
    with op.batch_alter_table('controllers', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_controllers_station_id'))
        batch_op.drop_index(batch_op.f('ix_controllers_id'))
        batch_op.drop_index(batch_op.f('ix_controllers_device_uid'))
        batch_op.drop_index(batch_op.f('ix_controllers_controller_code'))

    op.drop_table('controllers')
    with op.batch_alter_table('audit_logs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_audit_logs_station_id'))
        batch_op.drop_index(batch_op.f('ix_audit_logs_site_id'))
        batch_op.drop_index('ix_audit_logs_resource_type_resource_id')
        batch_op.drop_index(batch_op.f('ix_audit_logs_resource_id'))
        batch_op.drop_index('ix_audit_logs_organization_id_occurred_at')
        batch_op.drop_index(batch_op.f('ix_audit_logs_organization_id'))
        batch_op.drop_index(batch_op.f('ix_audit_logs_id'))
        batch_op.drop_index(batch_op.f('ix_audit_logs_actor_user_id'))

    op.drop_table('audit_logs')
    with op.batch_alter_table('stations', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_stations_status'))
        batch_op.drop_index(batch_op.f('ix_stations_station_code'))
        batch_op.drop_index(batch_op.f('ix_stations_site_id'))
        batch_op.drop_index(batch_op.f('ix_stations_id'))

    op.drop_table('stations')
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_role'))
        batch_op.drop_index(batch_op.f('ix_users_organization_id'))
        batch_op.drop_index(batch_op.f('ix_users_id'))
        batch_op.drop_index(batch_op.f('ix_users_email'))

    op.drop_table('users')
    with op.batch_alter_table('sites', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_sites_status'))
        batch_op.drop_index(batch_op.f('ix_sites_site_code'))
        batch_op.drop_index(batch_op.f('ix_sites_organization_id'))
        batch_op.drop_index(batch_op.f('ix_sites_id'))

    op.drop_table('sites')
    with op.batch_alter_table('organizations', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_organizations_status'))
        batch_op.drop_index(batch_op.f('ix_organizations_organization_code'))
        batch_op.drop_index(batch_op.f('ix_organizations_id'))

    op.drop_table('organizations')
    # ### end Alembic commands ###
